version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rust-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h17vjuggrpav"
s3_prefix = "sam-app-rust-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
