AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  RustLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures: ["x86_64"]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: build/
      Policies:
        - AmazonDynamoDBFullAccess

Outputs:
  FunctionName:
    Value: !Ref RustLambdaFunction
    Description: Best Function Ever.
